pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/pharos-kubelet-proxy-amd64
    dockerfile: Dockerfile
    auto_tag: true
    when:
      event: tag

  qemu-register:
    image: multiarch/qemu-user-static:register
    privileged: true
    when:
      event: tag

  docker-arm:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/pharos-kubelet-proxy-arm64
    dockerfile: Dockerfile.arm
    auto_tag: true
    when:
      event: tag

  qemu-reset:
    image: multiarch/qemu-user-static:register
    privileged: true
    command: [ "--reset"]
    when:
      event: tag
      status:  [ failure, success ]
